\tc\lib\c0l.obj+
cmd.obj+
memory+
iregtab+
instr+
..\alu.obj+
..\m6800\opfunc.obj+
..\m6801\opfunc.obj+
..\h6301\opfunc.obj+
..\m6805\opfunc.obj+
..\m6811\opfunc.obj+
..\h6301\optab+
..\h6301\reg+
..\..\CALLSTAC.OBJ+
..\..\COMMAND.OBJ+
..\..\CPU.OBJ+
..\..\ERROR.OBJ+
..\..\FILEIO.OBJ+
..\..\FPRINTHE.OBJ+
..\..\MAIN.OBJ+
..\..\SYMTAB.OBJ+
..\..\TTY.OBJ+
..\..\memsetl.obj
sim6800
/c/x/v
..\..\sim.lib+
\tc\lib\EMU.LIB+
\tc\lib\mathl.lib+
\tc\lib\cl.lib
